name: saber # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.11.4' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: desktop
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0
compression: lzo
donation: https://github.com/sponsors/adil192
source-code: https://github.com/adil192/saber
issues: https://github.com/adil192/saber/issues
contact: soumyadeepghosh2004@zohomail.in
architectures:
  - build-on: amd64
    build-for: amd64
package-repositories:
  - type: apt
    components: [jammy]
    suites: [prebuilt-mpr]
    key-id: B70EAE798718E0FE2972DD0C4FE9F2C43D9428A0
    url: https://proget.makedeb.org
parts:
  desktop:
    after: [saber]
    source: .
    plugin: dump
    prime:
      - snap/*
    parse-info: [$SNAP/meta/metainfo/com.adilhanney.saber.metainfo.xml]
  saber:
    source: https://github.com/adil192/saber.git
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: flutter
    #build-attributes: [enable-patchelf]
    build-packages:
      - rustup
      - jq
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
      - zenity
    override-pull: |
      craftctl default
      rustup default stable
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - saber
      - desktop
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gtk-common-themes" ; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  saber:
    command: saber
    desktop: snap/gui/saber.desktop
    extensions: [gnome]
    common-id: com.adilhanney.saber
    plugs:
      - home
      - network
      - network-status
